---
title: "Expected number of tests"
author: "Alexander V. Alekseyenko"
date: "8/20/2020"
output: html_document
---

Calculate expected number of tests under group testing of n negative individuals and $m$ positive individual, when testing in groups of $k$, for a total of $g=\lceil \frac{n+m}{k} \rceil$ groups.

```{r}
expected_tests_montecarlo = function(n, m, k, replicates = 100){
  f = c(rep(T,m), rep(F,n))
  pl = ifelse(length(f)%%k == 0, 0, k- length(f)%%k)
  res = replicate(replicates,
    sum(apply(matrix(c(sample(f), 
                       rep(F, pl)), ncol=k, byrow=T), 
              1,
              any)))
  mean(res)*k+ceiling((n+m)/k)
}
k = 5 # pool size

m = 10 # number of positive
n = 20-m # number of negative

(nt = expected_tests_montecarlo(n,m,k, 10))
n/nt
m/(n+m)
```


```{r}
m = 300 # number of positive
n = 5000-m # number of negative

(nt = expected_tests_montecarlo(n,m,k, 10))
n/nt
m/(n+m)
```

```{r}
m = 600 # number of positive
n = 5000-m # number of negative

(nt = expected_tests_montecarlo(n,m,k, 10))
n/nt
m/(n+m)
```



Exact calculation is below. It is too slow!!! Do not use for large n or m.
```{r}
expected_pools = function(n, m, k, iter=0){
  g = ceiling((n+m)/k)
#  print(c(iter, n,m,g,k))
  if(m == 0){
    return(0)
  }
  if(n == 0){
    return(g)
  }
  if(g == 1){
    return(1)
  }
  sum(sapply(0:k, function(i) 
    ifelse(n<k-i | m<i,
           0,
           dhyper(i, m, n, k)*((i>0)+expected_pools(n-k+i, m-i, k))))
    )
}
k = 5 # pool size

m = 10 # number of positive
n = 20-m # number of negative
g = ceiling((n+m)/k) # number of pools needed
(np = expected_pools(n, m, k))
(nt = (g+np*k))
n/nt
```

